apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pia-portforward.fullname" . }}
  labels:
    {{- include "pia-portforward.labels" . | nindent 4 }}
type: Opaque
stringData:
  pia-user: {{ .Values.pia.user | required "pia.user is required" | quote }}
  pia-password: {{ .Values.pia.password | required "pia.password is required" | quote }}
  {{- if .Values.qbittorrent.enabled }}
  qbittorrent-password: {{ .Values.qbittorrent.password | quote }}
  {{- end }}
